<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RootNamespace>zerg.core</RootNamespace>

        <PackageId>zerg.core</PackageId>
        <Title>zerg.core</Title>
        <Authors>Diogo Martins</Authors>
        <RepositoryUrl>https://github.com/MDA2AV/zerg</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <AssemblyVersion>0.5.26</AssemblyVersion>
        <FileVersion>0.5.26</FileVersion>
        <Version>0.5.26</Version>
        <PackageTags>io_uring</PackageTags>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <Description>Shared core library for zerg and terraform io_uring frameworks</Description>
        <PackageProjectUrl>https://github.com/MDA2AV/zerg</PackageProjectUrl>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\LICENSE">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="terraform" />
        <InternalsVisibleTo Include="zerg" />
        <InternalsVisibleTo Include="rtr" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.IO.Pipelines" Version="9.0.4" />
    </ItemGroup>

</Project>
