<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RootNamespace>Minima</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Magpie\Magpie.csproj" />
        <ProjectReference Include="..\RingPg\RingPg.csproj" />
    </ItemGroup>

</Project>
