<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>KestrelZerg.Demo</RootNamespace>
        <ServerGarbageCollection>true</ServerGarbageCollection>
        <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\KestrelZerg\KestrelZerg.csproj" />
    </ItemGroup>

</Project>
