<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Playground</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../src/ioxide/ioxide.csproj" />
    <ProjectReference Include="../src/ioxide.pg/ioxide.pg.csproj" />
    <ProjectReference Include="../src/ioxide.file/ioxide.file.csproj" />
    <ProjectReference Include="../src/ioxide.ngtcp2/ioxide.ngtcp2.csproj" />
    <ProjectReference Include="../src/ioxide.nghttp3/ioxide.nghttp3.csproj" />
    <ProjectReference Include="../src/ioxide.http3/ioxide.http3.csproj" />
    <ProjectReference Include="../src/ioxide.httpclient/ioxide.httpclient.csproj" />
  </ItemGroup>

</Project>
