<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Playground.Shared.Quic</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Shared/Playground.Shared.csproj" />
    <ProjectReference Include="../../src/protocols/ioxide.ngtcp2/ioxide.ngtcp2.csproj" />
  </ItemGroup>

</Project>
